
#ifndef FLAGS_H_
#define FLAGS_H_

enum SIGNAL_FLAG {
    SIGNAL_INPUT_LEFT = 1,
    SIGNAL_INPUT_RIGHT = 2,
    SIGNAL_INPUT_UP = 4,
    SIGNAL_INPUT_DOWN = 8,
    SIGNAL_FORCE_WAIT = 16,
    SIGNAL_FORCE_ATTACK = 32
};

#endif // FLAGS_H_
